In [1]:
from sklearn.feature_extraction.text import CountVectorizer , TfidfVectorizer , TfidfTransformer

In [2]:
text=['This is a line',
      'This is another line' , 
      'Completely different line']

# Count_Vectorizer

In [4]:
cnt_vctr=CountVectorizer()
sparse_mat=cnt_vctr.fit_transform(text)
sparse_mat

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [5]:
sparse_mat.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

In [6]:
cnt_vctr.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

# stop words

In [7]:
cv=CountVectorizer(stop_words='english')
cv.fit_transform(text)

<3x3 sparse matrix of type '<class 'numpy.int64'>'
	with 5 stored elements in Compressed Sparse Row format>

In [8]:
cv.vocabulary_

{'line': 2, 'completely': 0, 'different': 1}

# TfidfTransformer

In [10]:
cv=CountVectorizer()
count=cv.fit_transform(text)


tfidf_transformer=TfidfTransformer()
tfidf=tfidf_transformer.fit_transform(count)
tfidf.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

# pipe line for tfidf

In [11]:
from sklearn.pipeline import Pipeline

In [14]:
pipe=Pipeline([('cv' , CountVectorizer()) , ('tfidf' , TfidfTransformer())])

In [15]:
result=pipe.fit_transform(text)
result.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

# Tfidf_Vectorizer

In [16]:
tfidf=TfidfVectorizer(stop_words='english')
new=tfidf.fit_transform(text)
new.todense()

matrix([[0.        , 0.        , 1.        ],
        [0.        , 0.        , 1.        ],
        [0.65249088, 0.65249088, 0.38537163]])

In [17]:
tfidf.vocabulary_

{'line': 2, 'completely': 0, 'different': 1}