In [1]:
import numpy as np

## array

In [5]:
array_1=np.array([[1,2,3],[4,5,6]])

In [6]:
array_1

array([[1, 2, 3],
       [4, 5, 6]])

## arang

In [6]:
array_2=np.arange(1,100,3)

In [11]:
array_2

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

## zeros

In [9]:
array_3= np.zeros((4,3))

In [10]:
array_3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## ones

In [21]:
array_4= np.ones((4,4))

In [22]:
array_4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

## eye

In [28]:
array_5 = np.eye(5)

In [29]:
array_5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## linspace

In [26]:
array_6=np.linspace(0,10,21)

In [27]:
array_6

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

# random

## randتولید اعداد تصادفی با توزیع یکنواخت در بازه بسته 0و بازه باز 1

In [30]:
array_7= np.random.rand(4,2)

In [31]:
array_7

array([[0.9972743 , 0.31471079],
       [0.00562087, 0.80182369],
       [0.71701642, 0.59964933],
       [0.06873679, 0.43645956]])

## randn with mean = 0, std=1

In [34]:
array_8= np.random.randn(5,3)

In [35]:
array_8

array([[ 0.48508383,  0.37908099,  2.13332276],
       [-0.50246156, -0.77700355,  0.1461237 ],
       [-1.29985335, -1.28255045, -1.63489958],
       [ 0.635903  , -0.2411359 ,  1.2161008 ],
       [-0.51545382,  2.46758745,  0.96549869]])

## randint

In [36]:
array_9= np.random.randint(1,20,10)

In [37]:
array_9

array([ 9, 16, 10,  3, 14,  1,  2, 19,  5,  9])

In [38]:
array_10= np.random.randint(1,20,(3,4))

In [39]:
array_10

array([[12, 11,  5, 17],
       [12, 16, 17, 18],
       [ 7, 12, 18, 17]])

## seed

In [47]:
np.random.seed(42)
np.random.randint(4,123,(2,2))

array([[106,  55],
       [ 96,  18]])

## reshape

In [42]:
array_10.reshape(2,6)

array([[12, 11,  5, 17, 12, 16],
       [17, 18,  7, 12, 18, 17]])

## max , min

In [48]:
array_10.max()

18

In [49]:
array_10.min()

5

## argmax , argmin

In [50]:
array_10.argmax()

7

In [51]:
array_10.argmin()

2

## shape

In [55]:
array_5.shape

(5, 5)

## dtype

In [56]:
array_8.dtype

dtype('float64')

In [61]:
array_2.dtype

dtype('int32')

## indexing

In [9]:
arr=np.array([1,2,3,4])
arr[2]

3

In [10]:
arr[1::2]

array([2, 4])

In [11]:
arr[2:]=100,101
arr

array([  1,   2, 100, 101])

In [12]:
my_arr=np.random.randint(10,40,(4,3))
my_arr

array([[22, 14, 36],
       [12, 33, 18],
       [39, 11, 12],
       [34, 22, 24]])

In [13]:
my_arr[: :2 ,1]

array([14, 11])

## copy & deepcopy

In [14]:
arr_copy=arr.copy()
arr_copy[:2]=21,22
arr_copy

array([ 21,  22, 100, 101])

In [15]:
arr

array([  1,   2, 100, 101])

# Conditional selection

In [7]:
arr_1=np.arange(10).reshape(5,2)
arr_1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [8]:
arr_1[arr_1>4]

array([5, 6, 7, 8, 9])

# numpy_operations

## multiplay operation

In [35]:
array_01= np.random.randint(1,20,(4,4))
array_01

array([[ 8, 13, 16, 15],
       [12,  5, 11, 17],
       [ 2,  3,  2,  8],
       [12, 16, 16,  2]])

In [36]:
array_02=np.random.randint(0,10,(4,4))
array_02

array([[2, 6, 9, 3],
       [8, 1, 4, 0],
       [0, 7, 8, 4],
       [3, 9, 0, 6]])

In [37]:
array_01* array_02

array([[ 16,  78, 144,  45],
       [ 96,   5,  44,   0],
       [  0,  21,  16,  32],
       [ 36, 144,   0,  12]])

In [40]:
array_03=np.dot(arr_copy,array_02)
array_03

array([ 521, 1757, 1077, 1069])

## sqrt

In [41]:
np.sqrt(array_02)

array([[1.41421356, 2.44948974, 3.        , 1.73205081],
       [2.82842712, 1.        , 2.        , 0.        ],
       [0.        , 2.64575131, 2.82842712, 2.        ],
       [1.73205081, 3.        , 0.        , 2.44948974]])

## exp عدد نپر به توان می رسد

In [42]:
np.exp(array_02)

array([[7.38905610e+00, 4.03428793e+02, 8.10308393e+03, 2.00855369e+01],
       [2.98095799e+03, 2.71828183e+00, 5.45981500e+01, 1.00000000e+00],
       [1.00000000e+00, 1.09663316e+03, 2.98095799e+03, 5.45981500e+01],
       [2.00855369e+01, 8.10308393e+03, 1.00000000e+00, 4.03428793e+02]])

## sin

In [54]:
np.sin(90)

0.8939966636005579

In [55]:
np.sin(array_02)

array([[ 0.90929743, -0.2794155 ,  0.41211849,  0.14112001],
       [ 0.98935825,  0.84147098, -0.7568025 ,  0.        ],
       [ 0.        ,  0.6569866 ,  0.98935825, -0.7568025 ],
       [ 0.14112001,  0.41211849,  0.        , -0.2794155 ]])

## log

In [56]:
np.log(array_02)

C:\Users\Hasan\AppData\Local\Temp\ipykernel_3720\3427058148.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(array_02)


array([[0.69314718, 1.79175947, 2.19722458, 1.09861229],
       [2.07944154, 0.        , 1.38629436,       -inf],
       [      -inf, 1.94591015, 2.07944154, 1.38629436],
       [1.09861229, 2.19722458,       -inf, 1.79175947]])

## abs

In [57]:
np.abs(arr)

array([  1,   2, 100, 101])

## sum

In [58]:
arr.sum()

204

## mean

In [59]:
arr.mean()

51.0

## variance

In [61]:
arr.var()

2450.5

## standard deviation

In [65]:
arr.std()

49.502525188115406

## axis =0=x & axis=1=y & axis=2=z

In [67]:
array_01.sum(axis=0)

array([34, 37, 45, 42])

In [69]:
array_01.sum(axis=1)

array([52, 45, 15, 46])

## exercises

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [11]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [13]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [15]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
np.random.rand(1)

array([0.08194287])

In [18]:
np.random.randn(25)

array([ 1.64346774, -0.85363823,  0.22374127, -0.31413242, -0.88750881,
        0.18441473,  1.30629517,  1.07434108,  2.41483289, -0.04053652,
        2.64366275, -1.08046286,  0.63732989,  2.59073992,  2.92888022,
       -1.41600889, -0.56110667, -0.47471997, -0.89833   , -1.22247402,
       -0.438111  , -2.19080244,  0.34541661, -1.97777776,  0.64920594])

# **

In [26]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [27]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [30]:
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [31]:
mat[2: , 1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [32]:
mat[3 , 4]

20

In [37]:
mat[ :3, 1:2]

array([[ 2],
       [ 7],
       [12]])

In [38]:
mat[4 , :]

array([21, 22, 23, 24, 25])

In [39]:
mat[3:, :]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [40]:
mat.sum()

325

In [41]:
mat.var()

52.0

In [42]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [43]:
np.random.seed(101)